### ISSUE TITLE
Asteroids (mountains.png) look better if they have a defined edge

### ISSUE THREAD

**Issue by Gadgetoid** [Molesmalo/StarWarsMod4AirMash#1]
See attached for a quick and dirty example:

![mountains](https://user-images.githubusercontent.com/1746967/34679770-de0ef9b6-f48e-11e7-995a-05899f610ab1.png)

Not this also reveals areas where the "mountains" have gaps between them that aren't otherwise so obvious. Handy for strategic play in cover!

Since the collision detection "walls" (circles, actually) are just dots placed on the tips of every mountain, you might be able to make your asteroids still slightly smaller without it feeling too weird. Although being careful to avoid areas where it looks like it's possible to shoot between them but an invisible wall blocks the shot.

Here are the "walls" plotted on the original map:

![worldmap-data-2048x1024](https://user-images.githubusercontent.com/1746967/34680105-f5582876-f48f-11e7-9eb1-2467d2cd89ad.jpg)

**Comment by Molesmalo** [comment]
Hi, sorry I haven't seen this before!  I just checked using your png.

While in your picture the dots seem very sparse, if you activate the drawing of collision circles in the game (config.debug.collisions), you'll see that they actually overlap quite a lot... This means that having some opacity on the edges, allows for better blending, creating the illusion of bigger asteroids.  That's the same tactic used by the default mountains. Check this example (sorry for the overlapping sidebar).

![same_mountain](https://user-images.githubusercontent.com/34817589/34865035-d101f6a0-f755-11e7-8a2f-c04fae197cee.jpg)

And while it's bigger, from what I've seen, players learned to fly over the borders, because having those extra borders gives an "illusion of depth"... Because of the shape of the rocks, they fly over the borders (because it's "further away" and bump with the tip of the rock, that's closer. At least, that's what I "feel" when playing.

But thinking a little more about it, one possibility that I thought about is adding (eventually) more variety for the mountains,  and have them be chosen by a map function using their index (or if i want a finer control, I might just replace the definitions).

I'll think a little more about it before doing anything! Thanks for the suggestion!

**Comment by Molesmalo** [comment]
After adding parallax, i ended up going for mostly-solid edges =)
So, I'm closing this one!
